# cores/mupen64plus.cmake — libretro mupen64plus-next (Nintendo 64) core build.
#
# Mirrors the `platform=libnx` block from the upstream Makefile + Makefile.common
# in the libretro/mupen64plus-libretro-nx repository. Compiles the mupen64plus
# core, GLideN64 video plugin, RSP-HLE audio plugin, and a private slice of
# libretro-common into a STATIC library named `core_mupen64plus` so the player
# nro can link `retro_*` directly.
#
# Two upstream concerns are deferred for follow-up:
#
#   * Dynarec — upstream libnx uses NEW_DYNAREC=4 (aarch64 backend). That
#     backend pulls a code-gen step (asm_defines.c -> awk -> asm_defines_gas.h)
#     which is awkward to thread through CMake when cross-compiling for Switch.
#     This recipe ships interpreter-only (`-DNO_ASM`) so the core at least
#     boots; switching the dynarec on is a follow-up. Performance will be
#     unplayable until that lands.
#   * EGL / GL — devkitPro's Switch toolchain doesn't ship EGL or GLcoreARB
#     headers and there's no `switch-mesa` portlib in this install. We write
#     minimal stub headers so the static lib compiles, and weak no-op runtime
#     stubs so the nro links. The video plugin won't actually render until a
#     real GL/EGL impl is wired through libnx; until then, the core boots but
#     the framebuffer stays black.

include(FetchContent)

FetchContent_Declare(libretro_mupen64plus
    GIT_REPOSITORY https://github.com/libretro/mupen64plus-libretro-nx.git
    GIT_TAG        master
    GIT_SHALLOW    TRUE
    GIT_SUBMODULES ""           # disable: upstream paraLLEl-RDP/RSP submodules
    GIT_SUBMODULES_RECURSE FALSE)
FetchContent_MakeAvailable(libretro_mupen64plus)

# devkitPro's Switch toolchain doesn't ship EGL / GLcoreARB headers (the GL
# stack is via libnx's nvgl shim, which doesn't have a C header surface that
# upstream GLideN64 expects). Write minimal stubs into the build tree so the
# static lib compiles. Real GL function calls won't resolve at final-link
# time without a switch-mesa equivalent — that's a follow-up.
set(_M64_STUBS ${CMAKE_CURRENT_BINARY_DIR}/mupen64plus_egl_stubs)
file(MAKE_DIRECTORY ${_M64_STUBS}/EGL ${_M64_STUBS}/KHR)
file(WRITE ${_M64_STUBS}/EGL/egl.h
    "#ifndef MUPEN64PLUS_FOYER_EGL_STUB_H\n"
    "#define MUPEN64PLUS_FOYER_EGL_STUB_H\n"
    "#include <stdint.h>\n"
    "#ifdef __cplusplus\nextern \"C\" {\n#endif\n"
    "typedef void* EGLDisplay;\n"
    "typedef void* EGLContext;\n"
    "typedef void* EGLSurface;\n"
    "typedef void* EGLConfig;\n"
    "typedef void* EGLNativeDisplayType;\n"
    "typedef void* EGLNativeWindowType;\n"
    "typedef int   EGLBoolean;\n"
    "typedef int   EGLint;\n"
    "typedef void* EGLClientBuffer;\n"
    "typedef void* EGLImageKHR;\n"
    "#define EGL_DEFAULT_DISPLAY ((EGLNativeDisplayType)0)\n"
    "#define EGL_NO_DISPLAY      ((EGLDisplay)0)\n"
    "#define EGL_NO_CONTEXT      ((EGLContext)0)\n"
    "#define EGL_NO_SURFACE      ((EGLSurface)0)\n"
    "#define EGL_FALSE 0\n"
    "#define EGL_TRUE  1\n"
    "#define EGL_EXTENSIONS 0x3055\n"
    "#define EGL_VENDOR     0x3053\n"
    "#define EGL_VERSION    0x3054\n"
    "EGLDisplay eglGetDisplay(EGLNativeDisplayType);\n"
    "EGLBoolean eglInitialize(EGLDisplay, EGLint*, EGLint*);\n"
    "const char* eglQueryString(EGLDisplay, EGLint);\n"
    "void* eglGetProcAddress(const char*);\n"
    "#ifdef __cplusplus\n}\n#endif\n"
    "#endif\n")
file(WRITE ${_M64_STUBS}/EGL/eglext.h
    "#ifndef MUPEN64PLUS_FOYER_EGLEXT_STUB_H\n"
    "#define MUPEN64PLUS_FOYER_EGLEXT_STUB_H\n"
    "#include <EGL/egl.h>\n"
    "#endif\n")

# Runtime stubs: weak no-op implementations so the static lib links into the
# nro. The video plugin won't actually render until a real EGL/GL impl is
# wired through libnx — same caveat as upstream: needs switch-mesa equivalents.
file(WRITE ${_M64_STUBS}/foyer_mupen64plus_stubs.c
    "/* Auto-generated by cores/mupen64plus.cmake */\n"
    "#include <stddef.h>\n"
    "#include <zlib.h>\n"
    "/* EGL no-ops */\n"
    "void* eglGetDisplay(void* d) { (void)d; return NULL; }\n"
    "int   eglInitialize(void* d, int* a, int* b) { (void)d;(void)a;(void)b; return 0; }\n"
    "const char* eglQueryString(void* d, int n) { (void)d;(void)n; return \"\"; }\n"
    "void* eglGetProcAddress(const char* n) { (void)n; return NULL; }\n"
    "/* gz* no-ops — TxCache disk cache is non-functional without them, but\n"
    " * the path is gated behind GLideN64 texture-pack settings so the core\n"
    " * still boots without it. */\n"
    "gzFile gzopen(const char* p, const char* m) { (void)p;(void)m; return NULL; }\n"
    "int gzclose(gzFile f) { (void)f; return 0; }\n"
    "int gzeof(gzFile f) { (void)f; return 1; }\n"
    "int gzread(gzFile f, void* buf, unsigned len) { (void)f;(void)buf;(void)len; return 0; }\n"
    "int gzwrite(gzFile f, const void* buf, unsigned len) { (void)f;(void)buf;(void)len; return 0; }\n"
    "long gzseek(gzFile f, long off, int whence) { (void)f;(void)off;(void)whence; return -1; }\n")

set(_M64_ROOT      ${libretro_mupen64plus_SOURCE_DIR})
set(_M64_CORE      ${_M64_ROOT}/mupen64plus-core)
set(_M64_LIBRETRO  ${_M64_ROOT}/libretro)
set(_M64_COMM      ${_M64_ROOT}/libretro-common)
set(_M64_RSP       ${_M64_ROOT}/mupen64plus-rsp-hle)
set(_M64_AUDIO     ${_M64_ROOT}/custom/mupen64plus-core/plugin/audio_libretro)
set(_M64_GLN       ${_M64_ROOT}/GLideN64)
set(_M64_CUSTOM    ${_M64_ROOT}/custom)
set(_M64_MINIZIP   ${_M64_CORE}/subprojects/minizip)
set(_M64_LIBPNG    ${_M64_CUSTOM}/dependencies/libpng)
set(_M64_ZLIB      ${_M64_CUSTOM}/dependencies/libzlib)
set(_M64_XXHASH    ${_M64_ROOT}/xxHash)

# ---------------------------------------------------------------------------
# Source list — mupen64plus core (interpreter-only, libnx target)
# ---------------------------------------------------------------------------
set(_M64_CORE_C
    ${_M64_CORE}/src/api/callbacks.c
    ${_M64_CUSTOM}/mupen64plus-core/api/config.c
    ${_M64_CORE}/src/api/debugger.c
    ${_M64_CORE}/src/api/frontend.c
    ${_M64_CORE}/src/backends/plugins_compat/audio_plugin_compat.c
    ${_M64_CORE}/src/backends/api/video_capture_backend.c
    ${_M64_CORE}/src/backends/plugins_compat/input_plugin_compat.c
    ${_M64_CORE}/src/backends/clock_ctime_plus_delta.c
    ${_M64_CORE}/src/backends/dummy_video_capture.c
    ${_M64_CORE}/src/backends/file_storage.c
    ${_M64_CORE}/src/device/cart/cart.c
    ${_M64_CORE}/src/device/cart/af_rtc.c
    ${_M64_CORE}/src/device/cart/cart_rom.c
    ${_M64_CORE}/src/device/cart/eeprom.c
    ${_M64_CORE}/src/device/cart/flashram.c
    ${_M64_CORE}/src/device/cart/is_viewer.c
    ${_M64_CORE}/src/device/cart/sram.c
    ${_M64_CORE}/src/device/controllers/game_controller.c
    ${_M64_CORE}/src/device/controllers/vru_controller.c
    ${_M64_CORE}/src/device/controllers/paks/biopak.c
    ${_M64_CORE}/src/device/controllers/paks/mempak.c
    ${_M64_CORE}/src/device/controllers/paks/rumblepak.c
    ${_M64_CORE}/src/device/controllers/paks/transferpak.c
    ${_M64_CORE}/src/device/dd/dd_controller.c
    ${_M64_CORE}/src/device/dd/disk.c
    ${_M64_CORE}/src/device/device.c
    ${_M64_CORE}/src/device/gb/gb_cart.c
    ${_M64_CORE}/src/device/gb/mbc3_rtc.c
    ${_M64_CORE}/src/device/gb/m64282fp.c
    ${_M64_CORE}/src/device/memory/memory.c
    ${_M64_CORE}/src/device/pif/bootrom_hle.c
    ${_M64_CORE}/src/device/pif/cic.c
    ${_M64_CORE}/src/device/pif/n64_cic_nus_6105.c
    ${_M64_CORE}/src/device/pif/pif.c
    ${_M64_CORE}/src/device/r4300/cached_interp.c
    ${_M64_CORE}/src/device/r4300/cp0.c
    ${_M64_CORE}/src/device/r4300/cp1.c
    ${_M64_CORE}/src/device/r4300/cp2.c
    ${_M64_CORE}/src/device/r4300/idec.c
    ${_M64_CORE}/src/device/r4300/interrupt.c
    ${_M64_CORE}/src/device/r4300/pure_interp.c
    ${_M64_CORE}/src/device/r4300/r4300_core.c
    ${_M64_CORE}/src/device/r4300/tlb.c
    ${_M64_CORE}/src/device/rcp/ai/ai_controller.c
    ${_M64_CORE}/src/device/rcp/mi/mi_controller.c
    ${_M64_CORE}/src/device/rcp/pi/pi_controller.c
    ${_M64_CORE}/src/device/rcp/rdp/fb.c
    ${_M64_CORE}/src/device/rcp/rdp/rdp_core.c
    ${_M64_CORE}/src/device/rcp/ri/ri_controller.c
    ${_M64_CORE}/src/device/rcp/rsp/rsp_core.c
    ${_M64_CORE}/src/device/rcp/si/si_controller.c
    ${_M64_CORE}/src/device/rcp/vi/vi_controller.c
    ${_M64_CORE}/src/device/rdram/rdram.c
    ${_M64_CORE}/src/main/main.c
    ${_M64_CORE}/src/main/util.c
    ${_M64_CORE}/src/main/cheat.c
    ${_M64_CORE}/src/main/rom.c
    ${_M64_CORE}/src/main/savestates.c
    ${_M64_CORE}/src/plugin/plugin.c
    ${_M64_CORE}/src/plugin/dummy_audio.c
    ${_M64_CORE}/src/plugin/dummy_input.c
    ${_M64_CORE}/subprojects/md5/md5.c
)

# ---------------------------------------------------------------------------
# Vendored dependencies (libpng, minizip, zlib).
# Switch's portlibs ship a zlib but the core was tuned against this vendored
# copy, so we just compile what upstream compiles.
# ---------------------------------------------------------------------------
set(_M64_DEPS_C
    ${_M64_LIBPNG}/png.c
    ${_M64_LIBPNG}/pngerror.c
    ${_M64_LIBPNG}/pngget.c
    ${_M64_LIBPNG}/pngmem.c
    ${_M64_LIBPNG}/pngpread.c
    ${_M64_LIBPNG}/pngread.c
    ${_M64_LIBPNG}/pngrio.c
    ${_M64_LIBPNG}/pngrtran.c
    ${_M64_LIBPNG}/pngrutil.c
    ${_M64_LIBPNG}/pngset.c
    ${_M64_LIBPNG}/pngtrans.c
    ${_M64_LIBPNG}/pngwio.c
    ${_M64_LIBPNG}/pngwrite.c
    ${_M64_LIBPNG}/pngwtran.c
    ${_M64_LIBPNG}/pngwutil.c
    ${_M64_MINIZIP}/zip.c
    ${_M64_MINIZIP}/unzip.c
    ${_M64_MINIZIP}/ioapi.c
    ${_M64_ZLIB}/adler32.c
    ${_M64_ZLIB}/compress.c
    ${_M64_ZLIB}/crc32.c
    ${_M64_ZLIB}/deflate.c
    # NOTE: gz{close,lib,read,write}.c removed — they need posix read/write/
    # close/lseek which aren't declared via the vendored zlib's gzguts.h on
    # libnx. mupen64plus only needs deflate/inflate (zip + png), not gzio.
    ${_M64_ZLIB}/infback.c
    ${_M64_ZLIB}/inffast.c
    ${_M64_ZLIB}/inflate.c
    ${_M64_ZLIB}/inftrees.c
    ${_M64_ZLIB}/trees.c
    ${_M64_ZLIB}/uncompr.c
    ${_M64_ZLIB}/zutil.c
)

# ---------------------------------------------------------------------------
# Libretro frontend bridge + libretro-common subset (mirrors Makefile.common)
# ---------------------------------------------------------------------------
set(_M64_LIBRETRO_C
    ${_M64_LIBRETRO}/libretro.c
    ${_M64_COMM}/memmap/memalign.c
    ${_M64_CUSTOM}/mupen64plus-core/plugin/emulate_game_controller_via_libretro.c
    ${_M64_COMM}/audio/resampler/drivers/sinc_resampler.c
    ${_M64_COMM}/audio/resampler/drivers/nearest_resampler.c
    ${_M64_COMM}/audio/resampler/audio_resampler.c
    ${_M64_AUDIO}/audio_backend_libretro.c
    ${_M64_COMM}/file/config_file.c
    ${_M64_COMM}/file/config_file_userdata.c
    ${_M64_COMM}/file/file_path.c
    ${_M64_COMM}/file/file_path_io.c
    ${_M64_COMM}/time/rtime.c
    ${_M64_COMM}/compat/compat_strl.c
    ${_M64_COMM}/compat/compat_posix_string.c
    ${_M64_COMM}/compat/compat_strcasestr.c
    ${_M64_COMM}/audio/conversion/float_to_s16.c
    ${_M64_COMM}/audio/conversion/s16_to_float.c
    ${_M64_COMM}/features/features_cpu.c
    ${_M64_COMM}/lists/string_list.c
    ${_M64_COMM}/encodings/encoding_utf.c
    ${_M64_COMM}/string/stdstring.c
    ${_M64_COMM}/vfs/vfs_implementation.c
    ${_M64_COMM}/streams/file_stream.c
    ${_M64_COMM}/compat/fopen_utf8.c
    ${_M64_CUSTOM}/mupen64plus-core/api/vidext_libretro.c
    ${_M64_COMM}/glsm/glsm.c
    ${_M64_COMM}/libco/libco.c
    ${_M64_COMM}/glsym/glsym_gl.c
    ${_M64_COMM}/glsym/rglgen.c
)

# ---------------------------------------------------------------------------
# RSP HLE audio plugin
# ---------------------------------------------------------------------------
set(_M64_RSP_C
    ${_M64_RSP}/src/alist.c
    ${_M64_RSP}/src/alist_audio.c
    ${_M64_RSP}/src/alist_naudio.c
    ${_M64_RSP}/src/alist_nead.c
    ${_M64_RSP}/src/audio.c
    ${_M64_RSP}/src/cicx105.c
    ${_M64_RSP}/src/hle.c
    ${_M64_RSP}/src/hvqm.c
    ${_M64_RSP}/src/jpeg.c
    ${_M64_RSP}/src/memory.c
    ${_M64_RSP}/src/mp3.c
    ${_M64_RSP}/src/musyx.c
    ${_M64_RSP}/src/re2.c
    ${_M64_RSP}/src/plugin.c
)

# ---------------------------------------------------------------------------
# OSAL (POSIX flavour for libnx)
# ---------------------------------------------------------------------------
set(_M64_OSAL_C
    ${_M64_GLN}/src/osal/osal_files_unix.c
)

# ---------------------------------------------------------------------------
# GLideN64 (C++) — explicit list mirroring upstream Makefile.common.
# ---------------------------------------------------------------------------
set(_M64_GLN_CXX
    ${_M64_GLN}/src/Combiner.cpp
    ${_M64_GLN}/src/CombinerKey.cpp
    ${_M64_GLN}/src/CommonPluginAPI.cpp
    ${_M64_GLN}/src/Config.cpp
    ${_M64_GLN}/src/convert.cpp
    ${_M64_GLN}/src/DebugDump.cpp
    ${_M64_GLN}/src/Debugger.cpp
    ${_M64_GLN}/src/DepthBuffer.cpp
    ${_M64_GLN}/src/DisplayWindow.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp
    ${_M64_GLN}/src/DisplayLoadProgress.cpp
    ${_M64_GLN}/src/FrameBuffer.cpp
    ${_M64_GLN}/src/FrameBufferInfo.cpp
    ${_M64_GLN}/src/GBI.cpp
    ${_M64_GLN}/src/gDP.cpp
    ${_M64_GLN}/src/GLideN64.cpp
    ${_M64_GLN}/src/gSP.cpp
    ${_M64_GLN}/src/N64.cpp
    ${_M64_GLN}/src/TextDrawer.cpp
    ${_M64_GLN}/src/PaletteTexture.cpp
    ${_M64_GLN}/src/Performance.cpp
    ${_M64_GLN}/src/PostProcessor.cpp
    ${_M64_GLN}/src/RDP.cpp
    ${_M64_GLN}/src/RSP.cpp
    ${_M64_GLN}/src/SoftwareRender.cpp
    ${_M64_GLN}/src/TexrectDrawer.cpp
    ${_M64_GLN}/src/TextureFilterHandler.cpp
    ${_M64_GLN}/src/Textures.cpp
    ${_M64_GLN}/src/VI.cpp
    ${_M64_GLN}/src/ZlutTexture.cpp
    ${_M64_GLN}/src/common/CommonAPIImpl_common.cpp
    ${_M64_GLN}/src/DepthBufferRender/ClipPolygon.cpp
    ${_M64_GLN}/src/DepthBufferRender/DepthBufferRender.cpp
    ${_M64_GLN}/src/BufferCopy/BlueNoiseTexture.cpp
    ${_M64_GLN}/src/BufferCopy/ColorBufferToRDRAM.cpp
    ${_M64_GLN}/src/BufferCopy/DepthBufferToRDRAM.cpp
    ${_M64_GLN}/src/BufferCopy/RDRAMtoColorBuffer.cpp
    ${_M64_GLN}/src/GraphicsDrawer.cpp
    ${_M64_GLN}/src/Graphics/Context.cpp
    ${_M64_GLN}/src/Graphics/ColorBufferReader.cpp
    ${_M64_GLN}/src/Graphics/CombinerProgram.cpp
    ${_M64_GLN}/src/Graphics/ObjectHandle.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLFunctions.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_Wrapper.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_WrappedFunctions.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_Command.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_ObjectPool.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/ThreadedOpenGl/RingBufferPool.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_Attributes.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_BufferedDrawer.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_BufferManipulationObjectFactory.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_CachedFunctions.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithBufferStorage.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithPixelBuffer.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithReadPixels.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_GLInfo.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_Parameters.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_TextureManipulationObjectFactory.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_UnbufferedDrawer.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/opengl_Utils.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerInputs.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramImpl.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactory.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactoryAccurate.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactoryFast.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactoryCommon.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilderCommon.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilderAccurate.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilderFast.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_FXAA.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_ShaderStorage.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_SpecialShadersFactory.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GLSL/glsl_Utils.cpp
    ${_M64_GLN}/src/Graphics/OpenGLContext/GraphicBuffer/PrivateApi/GraphicBuffer.cpp
    ${_M64_GLN}/src/mupenplus/MemoryStatus_mupenplus.cpp
    ${_M64_GLN}/src/MupenPlusPluginAPI.cpp
    ${_M64_GLN}/src/mupenplus/MupenPlusAPIImpl.cpp
    ${_M64_GLN}/src/Log.cpp
    ${_M64_GLN}/src/3DMath.cpp
    ${_M64_GLN}/src/CRC32_ARMV8.cpp
    ${_M64_CUSTOM}/GLideN64/mupenplus/Config_mupenplus.cpp
    ${_M64_CUSTOM}/GLideN64/mupenplus/CommonAPIImpl_mupenplus.cpp
    # uCodes
    ${_M64_GLN}/src/uCodes/F3D.cpp
    ${_M64_GLN}/src/uCodes/F3DAM.cpp
    ${_M64_GLN}/src/uCodes/F3DBETA.cpp
    ${_M64_GLN}/src/uCodes/F3DDKR.cpp
    ${_M64_GLN}/src/uCodes/F3DEX.cpp
    ${_M64_GLN}/src/uCodes/F3DEX2.cpp
    ${_M64_GLN}/src/uCodes/F3DEX3.cpp
    ${_M64_GLN}/src/uCodes/F3DEX095.cpp
    ${_M64_GLN}/src/uCodes/F3DEX2ACCLAIM.cpp
    ${_M64_GLN}/src/uCodes/F3DEX2CBFD.cpp
    ${_M64_GLN}/src/uCodes/F3DZEX2.cpp
    ${_M64_GLN}/src/uCodes/F3DFLX2.cpp
    ${_M64_GLN}/src/uCodes/F3DGOLDEN.cpp
    ${_M64_GLN}/src/uCodes/F3DPD.cpp
    ${_M64_GLN}/src/uCodes/F3DSETA.cpp
    ${_M64_GLN}/src/uCodes/F5Indi_Naboo.cpp
    ${_M64_GLN}/src/uCodes/F5Rogue.cpp
    ${_M64_GLN}/src/uCodes/F3DTEXA.cpp
    ${_M64_GLN}/src/uCodes/L3D.cpp
    ${_M64_GLN}/src/uCodes/L3DEX2.cpp
    ${_M64_GLN}/src/uCodes/L3DEX.cpp
    ${_M64_GLN}/src/uCodes/S2DEX2.cpp
    ${_M64_GLN}/src/uCodes/S2DEX.cpp
    ${_M64_GLN}/src/uCodes/T3DUX.cpp
    ${_M64_GLN}/src/uCodes/Turbo3D.cpp
    ${_M64_GLN}/src/uCodes/ZSort.cpp
    ${_M64_GLN}/src/uCodes/ZSortBOSS.cpp
    # GLideNHQ texture filters
    ${_M64_GLN}/src/GLideNHQ/TextureFilters.cpp
    ${_M64_GLN}/src/GLideNHQ/TextureFilters_2xsai.cpp
    ${_M64_GLN}/src/GLideNHQ/TextureFilters_hq2x.cpp
    ${_M64_GLN}/src/GLideNHQ/TextureFilters_hq4x.cpp
    ${_M64_GLN}/src/GLideNHQ/TextureFilters_xbrz.cpp
    ${_M64_GLN}/src/GLideNHQ/TxCache.cpp
    ${_M64_GLN}/src/GLideNHQ/TxDbg.cpp
    ${_M64_GLN}/src/GLideNHQ/TxFilter.cpp
    ${_M64_GLN}/src/GLideNHQ/TxFilterExport.cpp
    ${_M64_GLN}/src/GLideNHQ/TxHiResCache.cpp
    ${_M64_GLN}/src/GLideNHQ/TxHiResNoCache.cpp
    ${_M64_GLN}/src/GLideNHQ/TxHiResLoader.cpp
    ${_M64_GLN}/src/GLideNHQ/TxImage.cpp
    ${_M64_GLN}/src/GLideNHQ/TxQuantize.cpp
    ${_M64_GLN}/src/GLideNHQ/TxReSample.cpp
    ${_M64_GLN}/src/GLideNHQ/TxTexCache.cpp
    ${_M64_GLN}/src/GLideNHQ/TxUtil.cpp
    ${_M64_GLN}/src/RSP_LoadMatrix.cpp
)

# ---------------------------------------------------------------------------
# Static library — mixed C / C++ / S
# ---------------------------------------------------------------------------
set(_M64_ALL_SRC
    ${_M64_CORE_C}
    ${_M64_DEPS_C}
    ${_M64_LIBRETRO_C}
    ${_M64_RSP_C}
    ${_M64_OSAL_C}
    ${_M64_GLN_CXX}
    ${_M64_STUBS}/foyer_mupen64plus_stubs.c
)

add_library(core_mupen64plus STATIC ${_M64_ALL_SRC})

target_include_directories(core_mupen64plus PUBLIC
    ${_M64_STUBS}
    ${_M64_CUSTOM}
    ${_M64_CUSTOM}/mupen64plus-core
    ${_M64_CUSTOM}/android/include
    ${_M64_CUSTOM}/GLideN64
    ${_M64_GLN}/src
    ${_M64_GLN}/src/osal
    ${_M64_GLN}/src/inc
    ${_M64_CORE}/src
    ${_M64_CORE}/src/api
    ${_M64_AUDIO}
    ${_M64_COMM}/include
    ${_M64_LIBRETRO}
    ${_M64_CORE}/subprojects/md5
    ${_M64_MINIZIP}
    ${_M64_LIBPNG}
    ${_M64_ZLIB}
    ${_M64_XXHASH}
)

target_compile_definitions(core_mupen64plus PRIVATE
    __LIBRETRO__=1
    SWITCH=1
    __SWITCH__=1
    HAVE_LIBNX=1
    HAVE_STDINT_H=1
    OS_LINUX
    EGL
    CORE
    HAVE_OPENGL
    USE_FILE32API
    M64P_PLUGIN_API
    M64P_CORE_PROTOTYPES
    M64P_STATIC_PLUGINS
    _ENDUSER_RELEASE
    SINC_LOWER_QUALITY
    TXFILTER_LIB
    __VEC4_OPT
    MUPENPLUSAPI
    __STDC_CONSTANT_MACROS
    __STDC_LIMIT_MACROS
    _GLIBCXX_USE_C99_MATH_TR1
    _LDBL_EQ_DBL
    _CRT_SECURE_NO_WARNINGS
    INLINE=inline
    PIC
    NDEBUG
    NO_ASM           # interpreter-only: drop dyna_jump/dyna_stop/dynarec_jump_to refs
)

target_compile_options(core_mupen64plus PRIVATE
    -w
    -fsigned-char
    -ffast-math
    -fno-strict-aliasing
    -fomit-frame-pointer
    -fvisibility=hidden
    -fcommon
    -funroll-loops
    -ffunction-sections
    -fdata-sections
)

# C-only flags
target_compile_options(core_mupen64plus PRIVATE
    $<$<COMPILE_LANGUAGE:C>:-Wno-discarded-qualifiers>
)
# C++-only flags (RTTI off matches upstream; visibility-inlines-hidden too).
target_compile_options(core_mupen64plus PRIVATE
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fvisibility-inlines-hidden>
)

set_target_properties(core_mupen64plus PROPERTIES
    C_STANDARD              99
    C_STANDARD_REQUIRED     ON
    CXX_STANDARD            17
    CXX_STANDARD_REQUIRED   ON
    POSITION_INDEPENDENT_CODE ON)
